spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_api
    username: postgres
    password: Eneye@chinu1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081